Efficiency: Efficiency.cc
	g++ -o Efficiency Efficiency.cc -O0 `root-config --cflags` `root-config --libs`

FiducialEff: FiducialEff.cc
	g++ -o FiducialEff FiducialEff.cc -O0 `root-config --cflags` `root-config --libs`

clean:
	rm ./Efficiency

